### ISSUE TITLE
Ubuntu 19.10: can't build sources

### ISSUE THREAD

**Issue by nmaster2042** [righthalfplane/SdrGlut#1]
Hi, I discovered your new soft and wanted to build it on my system.

Installad all deps but at build I get:

make: ***  No rule to make target « MainSource/agc.o », needed for « fireball ». Stop.

The only difference with your build note is I have home built SoapySDR 0.8 and libs are in /usr/local/lib

Hope you can help.

**Comment by righthalfplane** [comment]
Just delete "./MainSource/agc.o" from the makefile - it is not needed any longer. I forgot to delete it from the makefile.

**Comment by nmaster2042** [comment]
OK it does the trick.

Thank you very much.
