### ISSUE TITLE
Using SoapyAudio as the input source

### ISSUE THREAD

**Issue by NeuroForLunch** [righthalfplane/SdrGlut#22]
I installed it with brew and it shows up when I use SoapySDRUtil but it does not show up in SdrGlut. I'm using OSX Big Sur

<img width="301" alt="Screen Shot 2021-05-09 at 2 47 55 PM" src="https://user-images.githubusercontent.com/82769344/117588544-ce918580-b0d8-11eb-8650-8234aa18fa50.png">

<img width="376" alt="Screen Shot 2021-05-09 at 2 47 41 PM" src="https://user-images.githubusercontent.com/82769344/117588546-d18c7600-b0d8-11eb-8de8-06acb45d37f9.png">

<img width="678" alt="Screen Shot 2021-05-09 at 2 35 15 PM" src="https://user-images.githubusercontent.com/82769344/117588550-d8b38400-b0d8-11eb-8d61-c2a07a80da25.png">

**Comment by righthalfplane** [comment]
You should, now, be able to start a new conversation on the goggle group - or it it messed up ?

You should be able to copy the audio module from /usr/local/lib/SoapySDR/modules0.8/ to /Applications/SdrGlut.app/Contents/MacOS/lib/SoapySDR/modules0.8 and it should show up in the SdrGlut list, but how do you use it ?

I think that it will leave a better record - if we move to the goggle group.

**Comment by NeuroForLunch** [comment]
Closing this and moving it to the google group
