### ISSUE TITLE
Frequency units

### ISSUE THREAD

**Issue by perseus68-github** [righthalfplane/SdrGlut#24]
I'm wondering if the indicated Frequency could be displayed in MHz or even Hz and not in the actual  scientific format (i.e. 1.18E+08 Hz) which is not so intuitive

**Comment by righthalfplane** [comment]
Unless You are using a old version of SdrGlut - it uses MHZ in all but three places and only one of those should be used.

https://github.com/righthalfplane/SdrGlut/releases/tag/v1.25

**Comment by righthalfplane** [comment]
@perseus68-github

 It is in the latest version -

https://github.com/righthalfplane/SdrGlut/releases/tag/v1.26

**Comment by perseus68-github** [comment]
Thank you. I saw a screenshot with the change done. I'll download v1.26.

73s
