### ISSUE TITLE
user report

### ISSUE THREAD

**Issue by 9a4db** [righthalfplane/SdrGlut#4]
Just like to report that I am able to use older complied version
and fresh zip version on Ubuntu 18.04
Hardware is LimeNET micro remote on local network.
Transmit not yet tested because here use PCR 1000 IF on 10.7 like
preselector and up conversion to be able to RX from LW to SHF
Thank you for good work :+1: 
73
Djani

**Comment by righthalfplane** [comment]
Your Welcome.
