### ISSUE TITLE
Error trying to run the SdrGlut-521-uBuntu18.04.zip version

### ISSUE THREAD

**Issue by MaxQ73** [righthalfplane/SdrGlut#5]
Getting this error message when trying to run this version. I'm using Linux Mint 19.1.

./sdrglut.x: error while loading shared libraries: librtaudio.so.6: cannot open shared object file: No such file or directory

I don't see that file in the file list. There is librtaudio.so.6.1.0.

**Comment by righthalfplane** [comment]
You need to start sdrglut.x by running the script -

runSdrGlut.sh

It sets up the environment needed to run the program.
Running sdrglut.x directly will not work.

If you get the same error - rename  librtaudio.so.6.1.0 to  librtaudio.so.6.

If you still get an error - let me know - Linuix Mint must be doing some thing different from uBuntu.

**Comment by MaxQ73** [comment]
It failed when I tried to run the script, so I ran the commands in the script individually in a terminal in order to see the error message.

I renamed librtaudio.so.6.1.0 to librtaudio.so.6 and it is running now.
