### ISSUE TITLE
Undefined symbols for architecture x86_64 on macOS Catalina

### ISSUE THREAD

**Issue by nrcharles** [righthalfplane/SdrGlut#6]
Built rtaudio and liquid-dsp from source but fails on link. 

➜  SdrGlut git:(master) ✗ c++ -DNO_FORTRAN  -I/usr/X11R6/include  -I./DrawFindPointHistory -I./MainSource -I./KdTree-routines -I./glui-routines/include -I./CExpress -Wall  -o sdrglut.x -g ./MainSource/Getpalette.o ./MainSource/mThread.o ./MainSource/Scene.o  ./MainSource/Utilities.o ./DrawFindPointHistory/GridPlot.o ./CExpress/FFT2.o ./CExpress/Utilities2.o ./MainSource/BackgroundQ.o ./MainSource/cMalloc.o ./MainSource/SceneList.o ./MainSource/sceneDisplay.o  ./glui-routines/algebra3.o ./glui-routines/arcball.o ./glui-routines/glui.o ./glui-routines/glui_add_controls.o ./glui-routines/glui_bitmap_img_data.o ./glui-routines/glui_bitmaps.o ./glui-routines/glui_button.o ./glui-routines/glui_checkbox.o ./glui-routines/glui_column.o ./glui-routines/glui_commandline.o ./glui-routines/glui_control.o ./glui-routines/glui_edittext.o ./glui-routines/glui_filebrowser.o ./glui-routines/glui_list.o ./glui-routines/glui_listbox.o ./glui-routines/glui_mouse_iaction.o ./glui-routines/glui_node.o ./glui-routines/glui_panel.o ./glui-routines/glui_radio.o ./glui-routines/glui_rollout.o ./glui-routines/glui_rotation.o ./glui-routines/glui_scrollbar.o ./glui-routines/glui_separator.o ./glui-routines/glui_spinner.o ./glui-routines/glui_statictext.o ./glui-routines/glui_string.o ./glui-routines/glui_textbox.o ./glui-routines/glui_translation.o       ./glui-routines/glui_tree.o ./glui-routines/glui_treepanel.o       ./glui-routines/glui_window.o ./glui-routines/quaternion.o      ./glui-routines/tools/ppm.o ./MainSource/QuitDialog.o ./MainSource/main.o  ./MainSource/audiolib.o ./Classes/CWindow.o ./Classes/fastfir.o  ./Classes/fft.o ./Classes/CLines.o ./Classes/CLInesPlotLabels.o ./Classes/ClinesAttributes.o ./Classes/ClinesPlotAttributes.o ./Radio/smeter.o ./Classes/CLinesPlotBox.o ./Radio/Radio.o ./Radio/DialogRadio.o ./Radio/RaceFastsdr.o ./MainSource/DialogFileOpen.o ./SdrFile/SdrFile.o ./MainSource/DialogSave.o ./SdrFile/DialogSdrFile.o ./MainSource/fir.o ./MainSource/DialogFolder.o ./MainSource/PlayIQ.o ./MainSource/RecordIQ.o ./MainSource/printInfo.o -lm -L/usr/local -L/opt/X11/lib -lX11 -lglut -lgl -lglu -framework OpenGL -framework GLUT -framework OpenAL -lliquid -lSoapySDR
Undefined symbols for architecture x86_64:
  "freeMemoryTransmit(TransmitData*)", referenced from:
      Radio::~Radio() in Radio.o
  "Radio::setFrequency(double)", referenced from:
      Radio::setFrequency(playData*) in Radio.o
  "Radio::Transmit(Scene*)", referenced from:
      Radio::mMenuSelectl(Scene*, int) in Radio.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by righthalfplane** [comment]
There is a missing "./Classes/Transmit.o" in CCOBJS and a missing  -lrtaudio on the link line.

I have attached a zipped version of the corrected file.


[makefileMACINTOSH.zip](https://github.com/righthalfplane/SdrGlut/files/4364634/makefileMACINTOSH.zip)

**Comment by nrcharles** [comment]
That fixed it! Thanks!
