### ISSUE TITLE
make -f makefileMACINTOSH fails

### ISSUE THREAD

**Issue by bethanysciences** [righthalfplane/SdrGlut#9]
macOS Catalina 10.15.4 (19E287)  
  
bottom of message:  
```bash  
ld: warning: directory not found for option '-L/usr/X11/lib'
ld: library not found for -lX11
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fireball] Error 1
```  
Also no sdrglut.x file after - just SdrGlut.xcodeproj and when I build SdrGlut.xcodeproj I get the following error:  
```bash  
Error Group
Library not found for -lglut.3
```

**Comment by righthalfplane** [comment]
You need to install  xQuartz -

https://www.xquartz.org/releases/

**Comment by bethanysciences** [comment]
Thanks - works as it should now.
